allow-dbg-in-tests = true
allow-expect-in-tests = true
allow-indexing-slicing-in-tests = true
allow-print-in-tests = true
allow-unwrap-in-tests = true
cognitive-complexity-threshold = 30
large-error-threshold = 256
msrv = "1.95.0"
too-many-arguments-threshold = 8
too-many-lines-threshold = 120
type-complexity-threshold = 300
