[package]
name = "use-header"
description = "Small HTTP header utilities for RustUse"
publish = true
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
rust-version.workspace = true
readme = "README.md"
keywords = ["http", "header", "web", "parser", "utility"]
categories = ["web-programming", "parsing"]

[lints]
workspace = true
