[package]
name = "use-mime"
description = "Small MIME type utilities for RustUse"
publish = true
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
rust-version.workspace = true
readme = "README.md"
keywords = ["mime", "content-type", "extension", "web", "utility"]
categories = ["web-programming", "parsing"]

[lints]
workspace = true
