name: Gitleaks

on:
    pull_request:
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    secret-scan:
        name: Secret Scan
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Run Gitleaks
              uses: gitleaks/gitleaks-action@518e4898c0cd1cc5d9aab6627a2eabd46e81d8da # v1.6.0
              with:
                  config-path: .gitleaks.toml
