[package]
name = "use-uri"
description = "Small URI utility primitives for RustUse"
publish = true
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
rust-version.workspace = true
readme = "README.md"
keywords = ["uri", "web", "parser", "string", "utility"]
categories = ["parsing", "web-programming"]

[lints]
workspace = true
